// Copyright © 2019 ${<OWNER>}
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package mgnes

func newInstructionSet() []*Instruction {
	lookup := []*Instruction{
		{"BRK", opBRK, amIMM, 7, AddrModeIMM}, {"ORA", opORA, amIZX, 6, AddrModeIZX}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"???", opNOP, amIMP, 3, AddrModeIMP}, {"ORA", opORA, amZP0, 3, AddrModeZP0}, {"ASL", opASL, amZP0, 5, AddrModeZP0}, {"???", opXXX, amIMP, 5, AddrModeIMP}, {"PHP", opPHP, amIMP, 3, AddrModeIMP}, {"ORA", opORA, amIMM, 2, AddrModeIMM}, {"ASL", opASL, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"ORA", opORA, amABS, 4, AddrModeABS}, {"ASL", opASL, amABS, 6, AddrModeABS}, {"???", opXXX, amIMP, 6, AddrModeIMP},
		{"BPL", opBPL, amREL, 2, AddrModeREL}, {"ORA", opORA, amIZY, 5, AddrModeIZY}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"ORA", opORA, amZPX, 4, AddrModeZPX}, {"ASL", opASL, amZPX, 6, AddrModeZPX}, {"???", opXXX, amIMP, 6, AddrModeIMP}, {"CLC", opCLC, amIMP, 2, AddrModeIMP}, {"ORA", opORA, amABY, 4, AddrModeABY}, {"???", opNOP, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 7, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"ORA", opORA, amABX, 4, AddrModeABX}, {"ASL", opASL, amABX, 7, AddrModeABX}, {"???", opXXX, amIMP, 7, AddrModeIMP},
		{"JSR", opJSR, amABS, 6, AddrModeABS}, {"AND", opAND, amIZX, 6, AddrModeIZX}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"BIT", opBIT, amZP0, 3, AddrModeZP0}, {"AND", opAND, amZP0, 3, AddrModeZP0}, {"ROL", opROL, amZP0, 5, AddrModeZP0}, {"???", opXXX, amIMP, 5, AddrModeIMP}, {"PLP", opPLP, amIMP, 4, AddrModeIMP}, {"AND", opAND, amIMM, 2, AddrModeIMM}, {"ROL", opROL, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"BIT", opBIT, amABS, 4, AddrModeABS}, {"AND", opAND, amABS, 4, AddrModeABS}, {"ROL", opROL, amABS, 6, AddrModeABS}, {"???", opXXX, amIMP, 6, AddrModeIMP},
		{"BMI", opBMI, amREL, 2, AddrModeREL}, {"AND", opAND, amIZY, 5, AddrModeIZY}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"AND", opAND, amZPX, 4, AddrModeZPX}, {"ROL", opROL, amZPX, 6, AddrModeZPX}, {"???", opXXX, amIMP, 6, AddrModeIMP}, {"SEC", opSEC, amIMP, 2, AddrModeIMP}, {"AND", opAND, amABY, 4, AddrModeABY}, {"???", opNOP, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 7, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"AND", opAND, amABX, 4, AddrModeABX}, {"ROL", opROL, amABX, 7, AddrModeABX}, {"???", opXXX, amIMP, 7, AddrModeIMP},
		{"RTI", opRTI, amIMP, 6, AddrModeIMP}, {"EOR", opEOR, amIZX, 6, AddrModeIZX}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"???", opNOP, amIMP, 3, AddrModeIMP}, {"EOR", opEOR, amZP0, 3, AddrModeZP0}, {"LSR", opLSR, amZP0, 5, AddrModeZP0}, {"???", opXXX, amIMP, 5, AddrModeIMP}, {"PHA", opPHA, amIMP, 3, AddrModeIMP}, {"EOR", opEOR, amIMM, 2, AddrModeIMM}, {"LSR", opLSR, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"JMP", opJMP, amABS, 3, AddrModeABS}, {"EOR", opEOR, amABS, 4, AddrModeABS}, {"LSR", opLSR, amABS, 6, AddrModeABS}, {"???", opXXX, amIMP, 6, AddrModeIMP},
		{"BVC", opBVC, amREL, 2, AddrModeREL}, {"EOR", opEOR, amIZY, 5, AddrModeIZY}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"EOR", opEOR, amZPX, 4, AddrModeZPX}, {"LSR", opLSR, amZPX, 6, AddrModeZPX}, {"???", opXXX, amIMP, 6, AddrModeIMP}, {"CLI", opCLI, amIMP, 2, AddrModeIMP}, {"EOR", opEOR, amABY, 4, AddrModeABY}, {"???", opNOP, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 7, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"EOR", opEOR, amABX, 4, AddrModeABX}, {"LSR", opLSR, amABX, 7, AddrModeABX}, {"???", opXXX, amIMP, 7, AddrModeIMP},
		{"RTS", opRTS, amIMP, 6, AddrModeIMP}, {"ADC", opADC, amIZX, 6, AddrModeIZX}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"???", opNOP, amIMP, 3, AddrModeIMP}, {"ADC", opADC, amZP0, 3, AddrModeZP0}, {"ROR", opROR, amZP0, 5, AddrModeZP0}, {"???", opXXX, amIMP, 5, AddrModeIMP}, {"PLA", opPLA, amIMP, 4, AddrModeIMP}, {"ADC", opADC, amIMM, 2, AddrModeIMM}, {"ROR", opROR, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"JMP", opJMP, amIND, 5, AddrModeIND}, {"ADC", opADC, amABS, 4, AddrModeABS}, {"ROR", opROR, amABS, 6, AddrModeABS}, {"???", opXXX, amIMP, 6, AddrModeIMP},
		{"BVS", opBVS, amREL, 2, AddrModeREL}, {"ADC", opADC, amIZY, 5, AddrModeIZY}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"ADC", opADC, amZPX, 4, AddrModeZPX}, {"ROR", opROR, amZPX, 6, AddrModeZPX}, {"???", opXXX, amIMP, 6, AddrModeIMP}, {"SEI", opSEI, amIMP, 2, AddrModeIMP}, {"ADC", opADC, amABY, 4, AddrModeABY}, {"???", opNOP, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 7, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"ADC", opADC, amABX, 4, AddrModeABX}, {"ROR", opROR, amABX, 7, AddrModeABX}, {"???", opXXX, amIMP, 7, AddrModeIMP},
		{"???", opNOP, amIMP, 2, AddrModeIMP}, {"STA", opSTA, amIZX, 6, AddrModeIZX}, {"???", opNOP, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 6, AddrModeIMP}, {"STY", opSTY, amZP0, 3, AddrModeZP0}, {"STA", opSTA, amZP0, 3, AddrModeZP0}, {"STX", opSTX, amZP0, 3, AddrModeZP0}, {"???", opXXX, amIMP, 3, AddrModeIMP}, {"DEY", opDEY, amIMP, 2, AddrModeIMP}, {"???", opNOP, amIMP, 2, AddrModeIMP}, {"TXA", opTXA, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"STY", opSTY, amABS, 4, AddrModeABS}, {"STA", opSTA, amABS, 4, AddrModeABS}, {"STX", opSTX, amABS, 4, AddrModeABS}, {"???", opXXX, amIMP, 4, AddrModeIMP},
		{"BCC", opBCC, amREL, 2, AddrModeREL}, {"STA", opSTA, amIZY, 6, AddrModeIZY}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 6, AddrModeIMP}, {"STY", opSTY, amZPX, 4, AddrModeZPX}, {"STA", opSTA, amZPX, 4, AddrModeZPX}, {"STX", opSTX, amZPY, 4, AddrModeZPY}, {"???", opXXX, amIMP, 4, AddrModeIMP}, {"TYA", opTYA, amIMP, 2, AddrModeIMP}, {"STA", opSTA, amABY, 5, AddrModeABY}, {"TXS", opTXS, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 5, AddrModeIMP}, {"???", opNOP, amIMP, 5, AddrModeIMP}, {"STA", opSTA, amABX, 5, AddrModeABX}, {"???", opXXX, amIMP, 5, AddrModeIMP}, {"???", opXXX, amIMP, 5, AddrModeIMP},
		{"LDY", opLDY, amIMM, 2, AddrModeIMM}, {"LDA", opLDA, amIZX, 6, AddrModeIZX}, {"LDX", opLDX, amIMM, 2, AddrModeIMM}, {"???", opXXX, amIMP, 6, AddrModeIMP}, {"LDY", opLDY, amZP0, 3, AddrModeZP0}, {"LDA", opLDA, amZP0, 3, AddrModeZP0}, {"LDX", opLDX, amZP0, 3, AddrModeZP0}, {"???", opXXX, amIMP, 3, AddrModeIMP}, {"TAY", opTAY, amIMP, 2, AddrModeIMP}, {"LDA", opLDA, amIMM, 2, AddrModeIMM}, {"TAX", opTAX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"LDY", opLDY, amABS, 4, AddrModeABS}, {"LDA", opLDA, amABS, 4, AddrModeABS}, {"LDX", opLDX, amABS, 4, AddrModeABS}, {"???", opXXX, amIMP, 4, AddrModeIMP},
		{"BCS", opBCS, amREL, 2, AddrModeREL}, {"LDA", opLDA, amIZY, 5, AddrModeIZY}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 5, AddrModeIMP}, {"LDY", opLDY, amZPX, 4, AddrModeZPX}, {"LDA", opLDA, amZPX, 4, AddrModeZPX}, {"LDX", opLDX, amZPY, 4, AddrModeZPY}, {"???", opXXX, amIMP, 4, AddrModeIMP}, {"CLV", opCLV, amIMP, 2, AddrModeIMP}, {"LDA", opLDA, amABY, 4, AddrModeABY}, {"TSX", opTSX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 4, AddrModeIMP}, {"LDY", opLDY, amABX, 4, AddrModeABX}, {"LDA", opLDA, amABX, 4, AddrModeABX}, {"LDX", opLDX, amABY, 4, AddrModeABY}, {"???", opXXX, amIMP, 4, AddrModeIMP},
		{"CPY", opCPY, amIMM, 2, AddrModeIMM}, {"CMP", opCMP, amIZX, 6, AddrModeIZX}, {"???", opNOP, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"CPY", opCPY, amZP0, 3, AddrModeZP0}, {"CMP", opCMP, amZP0, 3, AddrModeZP0}, {"DEC", opDEC, amZP0, 5, AddrModeZP0}, {"???", opXXX, amIMP, 5, AddrModeIMP}, {"INY", opINY, amIMP, 2, AddrModeIMP}, {"CMP", opCMP, amIMM, 2, AddrModeIMM}, {"DEX", opDEX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"CPY", opCPY, amABS, 4, AddrModeABS}, {"CMP", opCMP, amABS, 4, AddrModeABS}, {"DEC", opDEC, amABS, 6, AddrModeABS}, {"???", opXXX, amIMP, 6, AddrModeIMP},
		{"BNE", opBNE, amREL, 2, AddrModeREL}, {"CMP", opCMP, amIZY, 5, AddrModeIZY}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"CMP", opCMP, amZPX, 4, AddrModeZPX}, {"DEC", opDEC, amZPX, 6, AddrModeZPX}, {"???", opXXX, amIMP, 6, AddrModeIMP}, {"CLD", opCLD, amIMP, 2, AddrModeIMP}, {"CMP", opCMP, amABY, 4, AddrModeABY}, {"NOP", opNOP, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 7, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"CMP", opCMP, amABX, 4, AddrModeABX}, {"DEC", opDEC, amABX, 7, AddrModeABX}, {"???", opXXX, amIMP, 7, AddrModeIMP},
		{"CPX", opCPX, amIMM, 2, AddrModeIMM}, {"SBC", opSBC, amIZX, 6, AddrModeIZX}, {"???", opNOP, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"CPX", opCPX, amZP0, 3, AddrModeZP0}, {"SBC", opSBC, amZP0, 3, AddrModeZP0}, {"INC", opINC, amZP0, 5, AddrModeZP0}, {"???", opXXX, amIMP, 5, AddrModeIMP}, {"INX", opINX, amIMP, 2, AddrModeIMP}, {"SBC", opSBC, amIMM, 2, AddrModeIMM}, {"NOP", opNOP, amIMP, 2, AddrModeIMP}, {"???", opSBC, amIMP, 2, AddrModeIMP}, {"CPX", opCPX, amABS, 4, AddrModeABS}, {"SBC", opSBC, amABS, 4, AddrModeABS}, {"INC", opINC, amABS, 6, AddrModeABS}, {"???", opXXX, amIMP, 6, AddrModeIMP},
		{"BEQ", opBEQ, amREL, 2, AddrModeREL}, {"SBC", opSBC, amIZY, 5, AddrModeIZY}, {"???", opXXX, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 8, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"SBC", opSBC, amZPX, 4, AddrModeZPX}, {"INC", opINC, amZPX, 6, AddrModeZPX}, {"???", opXXX, amIMP, 6, AddrModeIMP}, {"SED", opSED, amIMP, 2, AddrModeIMP}, {"SBC", opSBC, amABY, 4, AddrModeABY}, {"NOP", opNOP, amIMP, 2, AddrModeIMP}, {"???", opXXX, amIMP, 7, AddrModeIMP}, {"???", opNOP, amIMP, 4, AddrModeIMP}, {"SBC", opSBC, amABX, 4, AddrModeABX}, {"INC", opINC, amABX, 7, AddrModeABX}, {"???", opXXX, amIMP, 7, AddrModeIMP},
	}
	return lookup
}
