// Copyright © 2019 ${<OWNER>}
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package mgnes

func newInstructionSet() []*Instruction {
	lookup := []*Instruction{
		{"BRK", opBRK, amIMM, 7, false}, {"ORA", opORA, amIZX, 6, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"???", opNOP, amIMP, 3, true}, {"ORA", opORA, amZP0, 3, false}, {"ASL", opASL, amZP0, 5, false}, {"???", opXXX, amIMP, 5, true}, {"PHP", opPHP, amIMP, 3, true}, {"ORA", opORA, amIMM, 2, false}, {"ASL", opASL, amIMP, 2, true}, {"???", opXXX, amIMP, 2, true}, {"???", opNOP, amIMP, 4, true}, {"ORA", opORA, amABS, 4, false}, {"ASL", opASL, amABS, 6, false}, {"???", opXXX, amIMP, 6, true},
		{"BPL", opBPL, amREL, 2, false}, {"ORA", opORA, amIZY, 5, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"???", opNOP, amIMP, 4, true}, {"ORA", opORA, amZPX, 4, false}, {"ASL", opASL, amZPX, 6, false}, {"???", opXXX, amIMP, 6, true}, {"CLC", opCLC, amIMP, 2, true}, {"ORA", opORA, amABY, 4, false}, {"???", opNOP, amIMP, 2, true}, {"???", opXXX, amIMP, 7, true}, {"???", opNOP, amIMP, 4, true}, {"ORA", opORA, amABX, 4, false}, {"ASL", opASL, amABX, 7, false}, {"???", opXXX, amIMP, 7, true},
		{"JSR", opJSR, amABS, 6, false}, {"AND", opAND, amIZX, 6, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"BIT", opBIT, amZP0, 3, false}, {"AND", opAND, amZP0, 3, false}, {"ROL", opROL, amZP0, 5, false}, {"???", opXXX, amIMP, 5, true}, {"PLP", opPLP, amIMP, 4, true}, {"AND", opAND, amIMM, 2, false}, {"ROL", opROL, amIMP, 2, true}, {"???", opXXX, amIMP, 2, true}, {"BIT", opBIT, amABS, 4, false}, {"AND", opAND, amABS, 4, false}, {"ROL", opROL, amABS, 6, false}, {"???", opXXX, amIMP, 6, true},
		{"BMI", opBMI, amREL, 2, false}, {"AND", opAND, amIZY, 5, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"???", opNOP, amIMP, 4, true}, {"AND", opAND, amZPX, 4, false}, {"ROL", opROL, amZPX, 6, false}, {"???", opXXX, amIMP, 6, true}, {"SEC", opSEC, amIMP, 2, true}, {"AND", opAND, amABY, 4, false}, {"???", opNOP, amIMP, 2, true}, {"???", opXXX, amIMP, 7, true}, {"???", opNOP, amIMP, 4, true}, {"AND", opAND, amABX, 4, false}, {"ROL", opROL, amABX, 7, false}, {"???", opXXX, amIMP, 7, true},
		{"RTI", opRTI, amIMP, 6, true}, {"EOR", opEOR, amIZX, 6, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"???", opNOP, amIMP, 3, true}, {"EOR", opEOR, amZP0, 3, false}, {"LSR", opLSR, amZP0, 5, false}, {"???", opXXX, amIMP, 5, true}, {"PHA", opPHA, amIMP, 3, true}, {"EOR", opEOR, amIMM, 2, false}, {"LSR", opLSR, amIMP, 2, true}, {"???", opXXX, amIMP, 2, true}, {"JMP", opJMP, amABS, 3, false}, {"EOR", opEOR, amABS, 4, false}, {"LSR", opLSR, amABS, 6, false}, {"???", opXXX, amIMP, 6, true},
		{"BVC", opBVC, amREL, 2, false}, {"EOR", opEOR, amIZY, 5, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"???", opNOP, amIMP, 4, true}, {"EOR", opEOR, amZPX, 4, false}, {"LSR", opLSR, amZPX, 6, false}, {"???", opXXX, amIMP, 6, true}, {"CLI", opCLI, amIMP, 2, true}, {"EOR", opEOR, amABY, 4, false}, {"???", opNOP, amIMP, 2, true}, {"???", opXXX, amIMP, 7, true}, {"???", opNOP, amIMP, 4, true}, {"EOR", opEOR, amABX, 4, false}, {"LSR", opLSR, amABX, 7, false}, {"???", opXXX, amIMP, 7, true},
		{"RTS", opRTS, amIMP, 6, true}, {"ADC", opADC, amIZX, 6, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"???", opNOP, amIMP, 3, true}, {"ADC", opADC, amZP0, 3, false}, {"ROR", opROR, amZP0, 5, false}, {"???", opXXX, amIMP, 5, true}, {"PLA", opPLA, amIMP, 4, true}, {"ADC", opADC, amIMM, 2, false}, {"ROR", opROR, amIMP, 2, true}, {"???", opXXX, amIMP, 2, true}, {"JMP", opJMP, amIND, 5, false}, {"ADC", opADC, amABS, 4, false}, {"ROR", opROR, amABS, 6, false}, {"???", opXXX, amIMP, 6, true},
		{"BVS", opBVS, amREL, 2, false}, {"ADC", opADC, amIZY, 5, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"???", opNOP, amIMP, 4, true}, {"ADC", opADC, amZPX, 4, false}, {"ROR", opROR, amZPX, 6, false}, {"???", opXXX, amIMP, 6, true}, {"SEI", opSEI, amIMP, 2, true}, {"ADC", opADC, amABY, 4, false}, {"???", opNOP, amIMP, 2, true}, {"???", opXXX, amIMP, 7, true}, {"???", opNOP, amIMP, 4, true}, {"ADC", opADC, amABX, 4, false}, {"ROR", opROR, amABX, 7, false}, {"???", opXXX, amIMP, 7, true},
		{"???", opNOP, amIMP, 2, true}, {"STA", opSTA, amIZX, 6, false}, {"???", opNOP, amIMP, 2, true}, {"???", opXXX, amIMP, 6, true}, {"STY", opSTY, amZP0, 3, false}, {"STA", opSTA, amZP0, 3, false}, {"STX", opSTX, amZP0, 3, false}, {"???", opXXX, amIMP, 3, true}, {"DEY", opDEY, amIMP, 2, true}, {"???", opNOP, amIMP, 2, true}, {"TXA", opTXA, amIMP, 2, true}, {"???", opXXX, amIMP, 2, true}, {"STY", opSTY, amABS, 4, false}, {"STA", opSTA, amABS, 4, false}, {"STX", opSTX, amABS, 4, false}, {"???", opXXX, amIMP, 4, true},
		{"BCC", opBCC, amREL, 2, false}, {"STA", opSTA, amIZY, 6, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 6, true}, {"STY", opSTY, amZPX, 4, false}, {"STA", opSTA, amZPX, 4, false}, {"STX", opSTX, amZPY, 4, false}, {"???", opXXX, amIMP, 4, true}, {"TYA", opTYA, amIMP, 2, true}, {"STA", opSTA, amABY, 5, false}, {"TXS", opTXS, amIMP, 2, true}, {"???", opXXX, amIMP, 5, true}, {"???", opNOP, amIMP, 5, true}, {"STA", opSTA, amABX, 5, false}, {"???", opXXX, amIMP, 5, true}, {"???", opXXX, amIMP, 5, true},
		{"LDY", opLDY, amIMM, 2, false}, {"LDA", opLDA, amIZX, 6, false}, {"LDX", opLDX, amIMM, 2, false}, {"???", opXXX, amIMP, 6, true}, {"LDY", opLDY, amZP0, 3, false}, {"LDA", opLDA, amZP0, 3, false}, {"LDX", opLDX, amZP0, 3, false}, {"???", opXXX, amIMP, 3, true}, {"TAY", opTAY, amIMP, 2, true}, {"LDA", opLDA, amIMM, 2, false}, {"TAX", opTAX, amIMP, 2, true}, {"???", opXXX, amIMP, 2, true}, {"LDY", opLDY, amABS, 4, false}, {"LDA", opLDA, amABS, 4, false}, {"LDX", opLDX, amABS, 4, false}, {"???", opXXX, amIMP, 4, true},
		{"BCS", opBCS, amREL, 2, false}, {"LDA", opLDA, amIZY, 5, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 5, true}, {"LDY", opLDY, amZPX, 4, false}, {"LDA", opLDA, amZPX, 4, false}, {"LDX", opLDX, amZPY, 4, false}, {"???", opXXX, amIMP, 4, true}, {"CLV", opCLV, amIMP, 2, true}, {"LDA", opLDA, amABY, 4, false}, {"TSX", opTSX, amIMP, 2, true}, {"???", opXXX, amIMP, 4, true}, {"LDY", opLDY, amABX, 4, false}, {"LDA", opLDA, amABX, 4, false}, {"LDX", opLDX, amABY, 4, false}, {"???", opXXX, amIMP, 4, true},
		{"CPY", opCPY, amIMM, 2, false}, {"CMP", opCMP, amIZX, 6, false}, {"???", opNOP, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"CPY", opCPY, amZP0, 3, false}, {"CMP", opCMP, amZP0, 3, false}, {"DEC", opDEC, amZP0, 5, false}, {"???", opXXX, amIMP, 5, true}, {"INY", opINY, amIMP, 2, true}, {"CMP", opCMP, amIMM, 2, false}, {"DEX", opDEX, amIMP, 2, true}, {"???", opXXX, amIMP, 2, true}, {"CPY", opCPY, amABS, 4, false}, {"CMP", opCMP, amABS, 4, false}, {"DEC", opDEC, amABS, 6, false}, {"???", opXXX, amIMP, 6, true},
		{"BNE", opBNE, amREL, 2, false}, {"CMP", opCMP, amIZY, 5, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"???", opNOP, amIMP, 4, true}, {"CMP", opCMP, amZPX, 4, false}, {"DEC", opDEC, amZPX, 6, false}, {"???", opXXX, amIMP, 6, true}, {"CLD", opCLD, amIMP, 2, true}, {"CMP", opCMP, amABY, 4, false}, {"NOP", opNOP, amIMP, 2, true}, {"???", opXXX, amIMP, 7, true}, {"???", opNOP, amIMP, 4, true}, {"CMP", opCMP, amABX, 4, false}, {"DEC", opDEC, amABX, 7, false}, {"???", opXXX, amIMP, 7, true},
		{"CPX", opCPX, amIMM, 2, false}, {"SBC", opSBC, amIZX, 6, false}, {"???", opNOP, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"CPX", opCPX, amZP0, 3, false}, {"SBC", opSBC, amZP0, 3, false}, {"INC", opINC, amZP0, 5, false}, {"???", opXXX, amIMP, 5, true}, {"INX", opINX, amIMP, 2, true}, {"SBC", opSBC, amIMM, 2, false}, {"NOP", opNOP, amIMP, 2, true}, {"???", opSBC, amIMP, 2, true}, {"CPX", opCPX, amABS, 4, false}, {"SBC", opSBC, amABS, 4, false}, {"INC", opINC, amABS, 6, false}, {"???", opXXX, amIMP, 6, true},
		{"BEQ", opBEQ, amREL, 2, false}, {"SBC", opSBC, amIZY, 5, false}, {"???", opXXX, amIMP, 2, true}, {"???", opXXX, amIMP, 8, true}, {"???", opNOP, amIMP, 4, true}, {"SBC", opSBC, amZPX, 4, false}, {"INC", opINC, amZPX, 6, false}, {"???", opXXX, amIMP, 6, true}, {"SED", opSED, amIMP, 2, true}, {"SBC", opSBC, amABY, 4, false}, {"NOP", opNOP, amIMP, 2, true}, {"???", opXXX, amIMP, 7, true}, {"???", opNOP, amIMP, 4, true}, {"SBC", opSBC, amABX, 4, false}, {"INC", opINC, amABX, 7, false}, {"???", opXXX, amIMP, 7, true},
	}
	return lookup
}
